import {
  updateAdventureCharacter,
  type AdventureCharacter,
  type AdventureItem,
} from "@gaulia/database";

import { ENERGY_MAX, ENERGY_REGEN_MS, HP_REGEN_MS, HP_REGEN_RATIO } from "../../data/pacing";
import { computeStats } from "./statsService";

/**
 * Health and energy are not regenerated by a background job: they are recomputed from `regenAt`
 * when the player acts, so one write is enough however many players sit idle.
 */
export function regeneratedVitals(
  character: AdventureCharacter,
  maxHp: number,
  now: number,
): { hp: number; energy: number; regenAt: Date } {
  const elapsed = Math.max(0, now - character.regenAt.getTime());

  const energy = Math.min(ENERGY_MAX, character.energy + Math.floor(elapsed / ENERGY_REGEN_MS));
  const hpPerTick = Math.max(1, Math.round(maxHp * HP_REGEN_RATIO));
  const hp = Math.min(maxHp, character.hp + Math.floor(elapsed / HP_REGEN_MS) * hpPerTick);

  // The leftover of the current period is not lost: `regenAt` only moves by the ticks actually
  // consumed, unless both gauges are full.
  const consumed = Math.min(
    energy >= ENERGY_MAX ? elapsed : Math.floor(elapsed / ENERGY_REGEN_MS) * ENERGY_REGEN_MS,
    hp >= maxHp ? elapsed : Math.floor(elapsed / HP_REGEN_MS) * HP_REGEN_MS,
  );

  return { hp, energy, regenAt: new Date(character.regenAt.getTime() + consumed) };
}

/** Persists the regeneration when it changed anything, and returns the up to date state. */
export async function refreshVitals(
  character: AdventureCharacter,
  items: AdventureItem[],
): Promise<AdventureCharacter> {
  const { maxHp } = computeStats(character, items);
  const vitals = regeneratedVitals(character, maxHp, Date.now());

  if (
    vitals.hp === character.hp &&
    vitals.energy === character.energy &&
    vitals.regenAt.getTime() === character.regenAt.getTime()
  ) {
    return character;
  }

  return updateAdventureCharacter(character.userId, vitals);
}

/** Milliseconds left before the next energy point (0 when the gauge is full). */
export function msUntilNextEnergy(character: AdventureCharacter, now: number): number {
  if (character.energy >= ENERGY_MAX) return 0;
  const elapsed = Math.max(0, now - character.regenAt.getTime());
  return ENERGY_REGEN_MS - (elapsed % ENERGY_REGEN_MS);
}
